version: '3.8'

services:
  Auth-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - /path/to/seq-data:/data
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped

  authservice:
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - "8081:8080"
      - "8082:8081"
    depends_on:
      - seq
      - Auth-db

  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8083:8080"
      - "8084:8081"
    depends_on:
      - seq

  dmservice:
    build:
      context: .
      dockerfile: DirectMessage/DirectMessageAPI/Dockerfile
    ports:
      - "8085:8080"
      - "8086:8081"
    depends_on:
      - seq

  healthservice:
    build:
      context: .
      dockerfile: HealthAPI/Dockerfile
    ports:
      - "9080:8080"
      - "9081:8081"
    depends_on:
      - seq 

  healthweb:
    build:
      context: .
      dockerfile: HealthWeb/Dockerfile
    ports:
      - "9082:8080"
      - "9083:8081"
    depends_on:
      - seq 

  likeservice:
    build:
      context: .
      dockerfile: Like/LikeAPI/Dockerfile
    ports:
      - "8087:8080"
      - "8088:8081"
    depends_on:
      - seq

  postservice:
    build:
      context: .
      dockerfile: Post/PostService/Dockerfile
    ports:
      - "8089:8080"
      - "8090:8081"
    depends_on:
      - seq
      - likeservice
  
  timelineservice:
    build:
      context: .
      dockerfile: Timeline/TimelineService/Dockerfile
    ports:
      - "8091:8080"
      - "8092:8081"
    depends_on:
      - seq
      - postservice

volumes:
  mssql-data:
