version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
      - "5341:5341"  
    volumes:
      - ./seq-data:/data  
    environment:
      - ACCEPT_EULA=Y  
    restart: unless-stopped