@UserService_HostAddress = https://localhost:7063

GET {{UserService_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{UserService_HostAddress}}/AddUser?username=string&password=string
Content-Type: application/json

{
  //UserDTO
}

###
